# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{textquery}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Grigorik"]
  s.date = %q{2010-07-26}
  s.description = %q{Evaluate any text against a collection of match rules}
  s.email = %q{ilya@igvita.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "benchmark/benchmark.rb",
     "benchmark/sample.txt",
     "examples/web.rb",
     "lib/textquery.rb",
     "lib/textquery/textquery.rb",
     "lib/textquery/textquery_grammar.treetop",
     "spec/textquery_spec.rb",
     "textquery.gemspec"
  ]
  s.homepage = %q{http://github.com/igrigorik/textquery}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{textquery}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Evaluate any text against a collection of match rules}
  s.test_files = [
    "spec/textquery_spec.rb",
     "examples/web.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<treetop>, [">= 0"])
    else
      s.add_dependency(%q<treetop>, [">= 0"])
    end
  else
    s.add_dependency(%q<treetop>, [">= 0"])
  end
end

